const now = '2026-03-11T08:00:00.000Z';

export const WIKI_FILTER_TAGS = [
  'Salle de bain',
  'WC',
  'Cuisine',
  'Chambre',
  'Escaliers & ascenseur',
  'Accès extérieurs',
  "Barres d'appui",
  'Ouvertures',
  'Equipements',
];

export const WIKI_LIBRARY_SEED = [
  {
    id: 'wiki-1',
    title: 'Douche de plain-pied',
    description: 'Receveur extra-plat, accès plus simple et limitation du risque de chute.',
    imageUrl: '/wiki-bathroom.svg',
    tags: ['Douche PMR', 'Salle de bain'],
    category: 'Salle de bain',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-2',
    title: 'Siege de douche rabattable',
    description: 'Permet une toilette assise avec un encombrement réduit hors usage.',
    imageUrl: '/wiki-bathroom.svg',
    tags: ['Douche PMR', 'Siege'],
    category: 'Salle de bain',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-3',
    title: "Barre d'appui verticale",
    description: 'Aide au relevage et à la stabilisation à l’entrée de douche ou près du lavabo.',
    imageUrl: '/wiki-bathroom.svg',
    tags: ["Barre d'appui", 'Salle de bain'],
    category: 'Salle de bain',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-4',
    title: 'Mitigeur thermostatique',
    description: 'Réglage plus sûr de la température et meilleure préhension.',
    imageUrl: '/wiki-bathroom.svg',
    tags: ['Salle de bain', 'Robinetterie'],
    category: 'Salle de bain',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-5',
    title: 'Receveur extra-plat antiderapant',
    description: 'Limite le ressaut et améliore la sécurité au transfert.',
    imageUrl: '/wiki-bathroom.svg',
    tags: ['Douche PMR', 'Sol anti derapant'],
    category: 'Salle de bain',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-6',
    title: 'WC sureleve',
    description: 'Hauteur d’assise augmentée pour faciliter le relevage.',
    imageUrl: '/wiki-wc.svg',
    tags: ['WC PMR'],
    category: 'WC',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-7',
    title: 'Barre de relevage WC',
    description: 'Appui latéral utile pour les transferts et le passage assis-debout.',
    imageUrl: '/wiki-wc.svg',
    tags: ['WC PMR', "Barre d'appui"],
    category: 'WC',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-8',
    title: 'Lave-mains compact accessible',
    description: 'Permet un usage proche du WC avec une meilleure accessibilité.',
    imageUrl: '/wiki-wc.svg',
    tags: ['WC PMR', 'Lavabo'],
    category: 'WC',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-9',
    title: 'Rampe de seuil',
    description: 'Compense un petit ressaut à l’entrée du logement ou d’une pièce.',
    imageUrl: '/wiki-access.svg',
    tags: ["Rampe d'accès", 'Seuil'],
    category: 'Acces',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-10',
    title: "Rampe d'acces exterieure",
    description: 'Rampe fixe ou modulaire pour franchir plusieurs marches à l’entrée.',
    imageUrl: '/wiki-access.svg',
    tags: ["Rampe d'accès", 'Exterieur'],
    category: 'Acces',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-11',
    title: 'Main courante exterieure',
    description: 'Sécurise les cheminements et les petites marches vers l’entrée.',
    imageUrl: '/wiki-access.svg',
    tags: ['Exterieur', 'Escalier'],
    category: 'Acces',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-12',
    title: 'Nez de marche contraste',
    description: 'Améliore le reperage visuel et limite le risque de chute dans l’escalier.',
    imageUrl: '/wiki-stairs.svg',
    tags: ['Escalier', 'Contraste'],
    category: 'Escalier',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-13',
    title: 'Main courante double',
    description: 'Appui bilateral utile dans les escaliers pour les personnes fragiles.',
    imageUrl: '/wiki-stairs.svg',
    tags: ['Escalier', "Barre d'appui"],
    category: 'Escalier',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-14',
    title: 'Monte-escalier droit',
    description: 'Solution assise pour un escalier simple avec palier bas et haut dégagés.',
    imageUrl: '/wiki-stairs.svg',
    tags: ['Monte escalier', 'Escalier'],
    category: 'Escalier',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-15',
    title: 'Monte-escalier courbe',
    description: 'Adapté aux escaliers avec virages ou paliers intermédiaires.',
    imageUrl: '/wiki-stairs.svg',
    tags: ['Monte escalier', 'Escalier'],
    category: 'Escalier',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-16',
    title: 'Plan de travail abaisse',
    description: 'Zone de préparation plus accessible en position assise ou avec aide technique.',
    imageUrl: '/wiki-kitchen.svg',
    tags: ['Cuisine adaptee'],
    category: 'Cuisine',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-17',
    title: 'Meubles bas a tiroirs',
    description: 'Accès plus simple au contenu qu’avec des placards profonds.',
    imageUrl: '/wiki-kitchen.svg',
    tags: ['Cuisine adaptee', 'Rangement'],
    category: 'Cuisine',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-18',
    title: 'Evier peu profond',
    description: 'Réduit l’effort d’atteinte et améliore l’usage en position assise.',
    imageUrl: '/wiki-kitchen.svg',
    tags: ['Cuisine adaptee', 'Evier'],
    category: 'Cuisine',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-19',
    title: 'Lit medicalise',
    description: 'Facilite les transferts, le positionnement et le relevage.',
    imageUrl: '/wiki-bedroom.svg',
    tags: ['Chambre', 'Transfert'],
    category: 'Chambre',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-20',
    title: 'Barre de redressement',
    description: 'Aide technique légère pour les couchers et le lever du lit.',
    imageUrl: '/wiki-bedroom.svg',
    tags: ['Chambre', "Barre d'appui"],
    category: 'Chambre',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-21',
    title: 'Volets roulants motorises',
    description: 'Réduit les efforts et évite les gestes douloureux au quotidien.',
    imageUrl: '/wiki-lighting.svg',
    tags: ['Motorisation', 'Volets'],
    category: 'Domotique',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-22',
    title: 'Portail motorise',
    description: 'Améliore l’accès extérieur sans effort de traction ou de poussée.',
    imageUrl: '/wiki-access.svg',
    tags: ['Motorisation', 'Exterieur'],
    category: 'Exterieur',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-23',
    title: 'Eclairage a detection',
    description: 'Balise les circulations et sécurise les levers nocturnes.',
    imageUrl: '/wiki-lighting.svg',
    tags: ['Eclairage', 'Circulation'],
    category: 'Domotique',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-24',
    title: 'Revêtement de sol antiderapant',
    description: 'Réduit le risque de glissade dans les zones humides ou de passage.',
    imageUrl: '/wiki-lighting.svg',
    tags: ['Sol anti derapant', 'Circulation'],
    category: 'Circulation',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-25',
    title: 'Elargissement de porte',
    description: 'Améliore le passage avec deambulateur, fauteuil ou aide humaine.',
    imageUrl: '/wiki-access.svg',
    tags: ['Porte', 'Circulation'],
    category: 'Circulation',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-26',
    title: 'Suppression de baignoire',
    description: 'Transformation d’une baignoire en douche accessible.',
    imageUrl: '/wiki-bathroom.svg',
    tags: ['Salle de bain', 'Douche PMR'],
    category: 'Salle de bain',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-27',
    title: 'Paroi de douche fixe',
    description: 'Limite les projections tout en gardant une entrée facile.',
    imageUrl: '/wiki-bathroom.svg',
    tags: ['Salle de bain', 'Douche PMR'],
    category: 'Salle de bain',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'wiki-28',
    title: 'Chemin lumineux nocturne',
    description: 'Repérage du trajet chambre-WC sans allumage complet.',
    imageUrl: '/wiki-lighting.svg',
    tags: ['Eclairage', 'Chambre'],
    category: 'Domotique',
    createdAt: now,
    updatedAt: now,
  },
];
